# Generated by Django 5.2.11 on 2026-02-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField(help_text='References the farmers.Farmer model (loose FK for now)')),
                ('task_type', models.CharField(help_text="e.g. 'Harvesting', 'Ploughing', 'Spraying'", max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('OFFERS_RECEIVED', 'Offers Received'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], db_index=True, default='REQUEST_CREATED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Worker Booking',
                'verbose_name_plural': 'Worker Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
