# Generated by Django 5.2.11 on 2026-02-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField(help_text='References the farmers.Farmer model (loose FK for now)')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('load_type', models.CharField(blank=True, default='', help_text="e.g. 'Grain bags', 'Vegetable crates'", max_length=200)),
                ('load_weight_kg', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('OFFERS_RECEIVED', 'Offers Received'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], db_index=True, default='REQUEST_CREATED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='transport.transport')),
            ],
            options={
                'verbose_name': 'Transport Booking',
                'verbose_name_plural': 'Transport Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
