# Generated by Django 4.2.28 on 2026-02-15 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0001_enhanced_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIHealthMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('response_time_ms', models.IntegerField()),
                ('status_code', models.IntegerField()),
                ('error_message', models.TextField(blank=True)),
                ('throughput_rps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_health_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('village', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farmers',
            },
        ),
        migrations.CreateModel(
            name='LandHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.CharField(choices=[('CLAY', 'Clay'), ('SANDY', 'Sandy'), ('LOAMY', 'Loamy'), ('SILTY', 'Silty'), ('BLACK', 'Black Soil'), ('RED', 'Red Soil')], max_length=50)),
                ('irrigation_type', models.CharField(choices=[('RAINFED', 'Rain Fed'), ('BOREWELL', 'Borewell'), ('CANAL', 'Canal'), ('DRIP', 'Drip Irrigation'), ('SPRINKLER', 'Sprinkler')], max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_holdings', to='farmers.farmer')),
            ],
            options={
                'db_table': 'land_holdings',
            },
        ),
        migrations.CreateModel(
            name='WeatherIntelligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rainfall_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rainfall_anomaly_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity_percent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('drought_risk_index', models.DecimalField(decimal_places=2, max_digits=3)),
                ('flood_risk_index', models.DecimalField(decimal_places=2, max_digits=3)),
                ('satellite_data_timestamp', models.DateTimeField()),
                ('alert_level', models.CharField(choices=[('INFO', 'Info'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather_intelligence',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=100)),
                ('workers_required', models.IntegerField()),
                ('workers_assigned', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('scheduled_date', models.DateField()),
                ('wage_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FULFILLED', 'Fulfilled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_bookings', to='farmers.farmer')),
            ],
            options={
                'db_table': 'worker_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cargo_type', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('vehicle_assigned', models.CharField(blank=True, max_length=100)),
                ('route_optimization_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('delay_risk', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='LOW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_bookings', to='farmers.farmer')),
            ],
            options={
                'db_table': 'transport_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nitrogen', models.DecimalField(decimal_places=2, help_text='kg/ha', max_digits=5)),
                ('phosphorus', models.DecimalField(decimal_places=2, help_text='kg/ha', max_digits=5)),
                ('potassium', models.DecimalField(decimal_places=2, help_text='kg/ha', max_digits=5)),
                ('ph_level', models.DecimalField(decimal_places=1, max_digits=3)),
                ('organic_carbon', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tested_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_reports', to='farmers.landholding')),
            ],
            options={
                'db_table': 'soil_reports',
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('DISEASE_OUTBREAK', 'Disease Outbreak'), ('WEATHER_EMERGENCY', 'Weather Emergency'), ('MARKET_CRASH', 'Market Crash'), ('TRANSPORT_DISRUPTION', 'Transport Disruption'), ('LABOR_SHORTAGE', 'Labor Shortage'), ('MODEL_DRIFT', 'Model Drift'), ('SYSTEM_FAILURE', 'System Failure')], max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MODERATE', 'Moderate'), ('INFO', 'Info')], max_length=20)),
                ('region', models.CharField(max_length=255)),
                ('affected_farmers_count', models.IntegerField(default=0)),
                ('estimated_impact_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommended_action', models.TextField()),
                ('source_system', models.CharField(max_length=50)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_alerts',
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='risk_alerts_severit_ab35ac_idx'), models.Index(fields=['alert_type'], name='risk_alerts_alert_t_ce2d64_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketPriceForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100)),
                ('mandi_location', models.CharField(max_length=255)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forecast_7d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forecast_14d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forecast_30d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volatility_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('model_version', models.CharField(max_length=20)),
                ('forecasted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_price_forecasts',
                'ordering': ['-forecasted_at'],
                'indexes': [models.Index(fields=['crop_name', 'mandi_location'], name='market_pric_crop_na_b16472_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('detected_disease', models.CharField(max_length=255)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('treatment_recommendation', models.TextField()),
                ('model_version', models.CharField(max_length=20)),
                ('false_positive_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_detections', to='farmers.farmer')),
            ],
            options={
                'db_table': 'disease_detections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='audit_logs_user_id_6193b2_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('CROP_RECOMMENDATION', 'Crop Recommendation'), ('DISEASE_TREATMENT', 'Disease Treatment'), ('MARKET_TIMING', 'Market Timing'), ('WEATHER_ACTION', 'Weather Action'), ('TRANSPORT_OPTIMIZATION', 'Transport Optimization'), ('WORKER_ALLOCATION', 'Worker Allocation')], max_length=50)),
                ('ai_recommendation', models.TextField()),
                ('estimated_yield_impact_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estimated_revenue_impact_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('required_resources', models.JSONField(blank=True, null=True)),
                ('execution_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('VERIFIED', 'Verified')], default='PENDING', max_length=50)),
                ('human_approval', models.BooleanField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_decisions', to='farmers.farmer')),
            ],
            options={
                'db_table': 'ai_decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AICropRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=20)),
                ('input_data', models.JSONField()),
                ('recommended_crops', models.JSONField()),
                ('confidence_scores', models.JSONField()),
                ('predicted_yield', models.JSONField(blank=True, null=True)),
                ('revenue_projection', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inference_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_recommendations', to='farmers.farmer')),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.landholding')),
            ],
            options={
                'db_table': 'ai_crop_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['district', 'state'], name='farmers_distric_64bdae_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['created_at'], name='farmers_created_1b8d85_idx'),
        ),
        migrations.AddIndex(
            model_name='aidecision',
            index=models.Index(fields=['execution_status'], name='ai_decision_executi_7ac3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='aicroprecommendation',
            index=models.Index(fields=['farmer', '-created_at'], name='ai_crop_rec_farmer__926f04_idx'),
        ),
    ]
