# Generated by Django 5.2.11 on 2026-02-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_initial'),
        ('farmers', '0003_hierarchy_and_views'),
    ]

    operations = [
    ]
