# Generated by Django 4.2.28 on 2026-03-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_merge_0002_initial_0003_hierarchy_and_views'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='farmer',
            name='idx_farmer_hierarchy',
        ),
    ]
