# Generated by Django 5.2.11 on 2026-02-28 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_id', models.UUIDField(blank=True, null=True)),
                ('n', models.FloatField()),
                ('p', models.FloatField()),
                ('k', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('recommended_crop', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_id', models.UUIDField(blank=True, null=True)),
                ('image_path', models.CharField(max_length=500)),
                ('disease', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(max_length=20)),
                ('risk_level', models.CharField(max_length=20)),
                ('model_version', models.CharField(max_length=50)),
                ('job_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('domain', models.CharField(choices=[('crop', 'Crop'), ('disease', 'Disease'), ('market', 'Market'), ('weather', 'Weather')], db_index=True, max_length=20)),
                ('model_version', models.CharField(max_length=50)),
                ('input_hash', models.CharField(max_length=16)),
                ('inference_ms', models.IntegerField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'created_at'], name='ai_predicti_domain_efcf75_idx')],
            },
        ),
    ]
